<div class="wrapper col3">
  					<div id="intro">
    				<div class="fl_left">
      				<h2>ARTES</h2>
      				<p>Da quasi un decennio, ARTES offre il miglior sistema in tempo reale di notifica d&#96;evacuazione dalld&#96;edificio in cui ti trovi.<br> </p>
      				<p class="readmore"><a href="#">Slideshow&raquo;</a></p>
    				</div>
    				<br class="clear"/>
  					</div>
					</div>
				    <br>	
				    <h1><b1>Mission</b1></h1>
				 <p>Il team ARTES, dall'acronimo Alert Real-Time Emergency System, è nato dall'esigenza sempre più diffusa di offrire un servizio 
      			di evacuazione personalizzato. Le emergenze in edifici di grosse dimensioni possono causare disordini e caos diffuso,
      			condizioni in cui l'incolumità della persona non è garantita. Con il sistema ARTEE, vi verrà notificato il percorso
      			d'evacuazione ottimale in base alla vostra posizione all'interno dell'edificio.</p>