Il team ARTES, dall'acronimo Alert Real-Time Emergency System, &egrave nato dall'esigenza sempre pi&ugrave diffusa di offrire un servizio 
      			di evacuazione personalizzato. Le emergenze in edifici di grosse dimensioni possono causare disordini e caos diffuso,
      			condizioni in cui l'incolumit&agrave della persona non &egrave garantita. Con il sistema ARTES, vi verr&agrave notificato il percorso
      			d&#96;evacuazione ottimale in base alla vostra posizione all&#96;interno dell'edificio.