<ul class="nav nav-collapse">
<li><a href="<?= $this->url(array(
					'controller'=>'admin',
					'action'=>'aggiungiutente',),
					'default',true);
					?>"
			title="Aggiunge un nuovo utente">Aggiungi Utente</a> 
	</li>
	<li><a href="<?= $this->url(array(
					'controller'=>'admin',
					'action'=>'seleziona',),
					'default',true);
					?>"
			title="Modifica informazioni utente esistente">Modifica Utente</a> 
	</li>
	<li><a href="<?= $this->url(array(
			'controller'=>'admin',
			'action'=>'modificautente',),
			'default',true);
		?>"
		   title="Gestisci planimetrie">Gestisci Planimetrie</a>
	</li>
	</ul>