<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Artes');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/font/css/fontello.css'); ?>
    <?php echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Droid+Sans:400,700'); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="<?= $this->url(array('controller'=>'public','action'=>'index',),'default',true);?>"><img src="<?php echo $this->baseUrl("img/shield icon.png")?>" alt=""></a>

            <?= $this->render('_navorizzontale.phtml')?>
            <div class="nav-collapse collapse"></div>
        </div>
    </div>
</div>



    <div class="container profile">
        <div class="span3"> <img src="<?php echo $this->baseUrl("img/mini.png")?>" alt=""> </div>
        <div class="span5">
            <h1>Artes</h1>
            <p><?php echo $this->layout()->content; ?> </p>
    </div>
    <div class="row social">
        <ul class="social-icons">
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/fb.png")?>"></a></li>
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/tw.png")?>"></a></li>
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/pin.png")?>"></a></li>
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/go.png")?>"></a></li>
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/st.png")?>"></a></li>
            <li><a href="#"><img src="<?php echo $this->baseUrl("img/dr.png")?>"></a></li>

        </ul>
    </div>
    <div class="footer" href="css/bootstrap-responsive.css" rel="stylesheet" type="text/css">
        <div class="container">
            <p><a href="#myModal" role="button" data-toggle="modal"> <i class="icon-mail"></i> CONTATTACI</a></p>
        </div>
    </div>
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3 id="myModalLabel"><i class="icon-mail"></i>Login</h3>
        </div>
        <div class="modal-body">
            <form action="#">
                <input type="text" placeholder="Username">
                <input type="text" placeholder="Password">
                <br>
                <button type="submit" class="btn btn-large"><i class="icon-paper-plane"></i> ENTRA</button>
            </form>
        </div>


    <script src="<?php echo $this->baseUrl("js/jquery-1.10.1.min.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/bootstrap.min.js")?>"></script>
    <script>
        $('#myModal').modal('hidden')
    </script>
</body>
</html>

